/* ============================================================
   Édito B1 — extracted content (Units 1–3 = approved template)
   Pushed into the arrays declared in edito.js.
============================================================ */

/* ---------------- WORDS ---------------- */
EDITO_WORDS.push(
/* — Unité 1 — Faire connaissance — */
{unit:1,theme:"Les moments de la vie",fr:"l'adolescence (f.)",ipa:"ladɔlɛsɑ̃s",ua:"підлітковий вік, юність",en:"adolescence",de:"die Jugend"},
{unit:1,theme:"Les moments de la vie",fr:"les anciens = les aînés",ipa:"lez‿ɑ̃sjɛ̃ le zene",ua:"люди похилого віку; старші",en:"the elderly; the elders",de:"die Alten, die Älteren"},
{unit:1,theme:"Les moments de la vie",fr:"l'enfance (f.)",ipa:"lɑ̃fɑ̃s",ua:"дитинство",en:"childhood",de:"die Kindheit"},
{unit:1,theme:"Les moments de la vie",fr:"la génération",ipa:"la ʒeneʁasjɔ̃",ua:"покоління",en:"generation",de:"die Generation"},
{unit:1,theme:"Les moments de la vie",fr:"grandir",ipa:"ɡʁɑ̃diʁ",ua:"рости, дорослішати",en:"to grow up",de:"aufwachsen"},
{unit:1,theme:"Les moments de la vie",fr:"la maison de retraite",ipa:"la mɛzɔ̃ də ʁətʁɛt",ua:"будинок для літніх людей",en:"retirement home",de:"das Altersheim"},
{unit:1,theme:"Les moments de la vie",fr:"naître",ipa:"nɛtʁ",ua:"народжуватися",en:"to be born",de:"geboren werden"},
{unit:1,theme:"Les membres de la famille",fr:"l'arrière-petit-fils, l'arrière-petite-fille",ipa:"laʁjɛʁ pəti fis",ua:"правнук, правнучка",en:"great-grandson, -daughter",de:"der Urenkel, die Urenkelin"},
{unit:1,theme:"Les membres de la famille",fr:"le beau-père, la belle-mère",ipa:"lə bo pɛʁ, la bɛl mɛʁ",ua:"тесть/свекор, теща/свекруха",en:"father-/mother-in-law",de:"der Schwiegervater, die Schwiegermutter"},
{unit:1,theme:"Les membres de la famille",fr:"la belle-famille",ipa:"la bɛl famij",ua:"родина чоловіка/дружини",en:"the in-laws",de:"die Schwiegerfamilie"},
{unit:1,theme:"Les membres de la famille",fr:"le/la cousin(e)",ipa:"lə la kuzɛ̃, kuzin",ua:"двоюрідний брат/сестра",en:"cousin",de:"der Cousin, die Cousine"},
{unit:1,theme:"Les membres de la famille",fr:"le frère, la sœur = la fratrie",ipa:"lə fʁɛʁ, la sœʁ",ua:"брат, сестра = брати й сестри",en:"brother, sister = siblings",de:"der Bruder, die Schwester = die Geschwister"},
{unit:1,theme:"Les membres de la famille",fr:"le gendre, la belle-fille",ipa:"lə ʒɑ̃dʁ, la bɛl fij",ua:"зять, невістка",en:"son-in-law, daughter-in-law",de:"der Schwiegersohn, die Schwiegertochter"},
{unit:1,theme:"Les membres de la famille",fr:"la grand-mère = la mamie",ipa:"la ɡʁɑ̃ mɛʁ",ua:"бабуся",en:"grandmother = granny",de:"die Großmutter = die Oma"},
{unit:1,theme:"Les membres de la famille",fr:"le grand-père = le papi",ipa:"lə ɡʁɑ̃ pɛʁ",ua:"дідусь",en:"grandfather = grandpa",de:"der Großvater = der Opa"},
{unit:1,theme:"Les membres de la famille",fr:"les grands-parents",ipa:"le ɡʁɑ̃ paʁɑ̃",ua:"дідусь і бабуся",en:"grandparents",de:"die Großeltern"},
{unit:1,theme:"Les membres de la famille",fr:"le neveu, la nièce",ipa:"lə nəvø, la njɛs",ua:"племінник, племінниця",en:"nephew, niece",de:"der Neffe, die Nichte"},
{unit:1,theme:"Les membres de la famille",fr:"l'oncle (m.), la tante",ipa:"lɔ̃kl, la tɑ̃t",ua:"дядько, тітка",en:"uncle, aunt",de:"der Onkel, die Tante"},
{unit:1,theme:"Les membres de la famille",fr:"le petit-fils, la petite-fille",ipa:"lə pəti fis, la pətit fij",ua:"онук, онука",en:"grandson, granddaughter",de:"der Enkel, die Enkelin"},
{unit:1,theme:"Les membres de la famille",fr:"les petits-enfants",ipa:"le pəti zɑ̃fɑ̃",ua:"онуки",en:"grandchildren",de:"die Enkelkinder"},
{unit:1,theme:"Les relations familiales",fr:"le divorce",ipa:"lə divɔʁs",ua:"розлучення",en:"divorce",de:"die Scheidung"},
{unit:1,theme:"Les relations familiales",fr:"être seul(e) ≠ en couple",ipa:"ɛtʁ sœl, ɑ̃ kupl",ua:"бути самотнім ≠ у парі",en:"to be single ≠ in a relationship",de:"allein ≠ in einer Beziehung sein"},
{unit:1,theme:"Les relations familiales",fr:"la famille nombreuse",ipa:"la famij nɔ̃bʁøz",ua:"багатодітна сім'я",en:"large family",de:"die kinderreiche Familie"},
{unit:1,theme:"Les relations familiales",fr:"se fiancer",ipa:"sə fjɑ̃se",ua:"заручитися",en:"to get engaged",de:"sich verloben"},
{unit:1,theme:"Les relations familiales",fr:"se marier",ipa:"sə maʁje",ua:"одружуватися",en:"to get married",de:"heiraten"},
{unit:1,theme:"Les relations familiales",fr:"la séparation",ipa:"la sepaʁasjɔ̃",ua:"розставання",en:"separation",de:"die Trennung"},
{unit:1,theme:"Les relations familiales",fr:"tomber/être enceinte",ipa:"tɔ̃be, ɛtʁ ɑ̃sɛ̃t",ua:"завагітніти / бути вагітною",en:"to get/be pregnant",de:"schwanger werden/sein"},
{unit:1,theme:"Les relations familiales",fr:"la tribu",ipa:"la tʁiby",ua:"плем'я; велика родина",en:"tribe; clan",de:"der Stamm, die Sippe"},
{unit:1,theme:"L'amour",fr:"l'âme sœur (f.)",ipa:"lɑm sœʁ",ua:"споріднена душа",en:"soulmate",de:"die Seelenverwandte"},
{unit:1,theme:"L'amour",fr:"(tomber) amoureux, amoureuse",ipa:"tɔ̃be amuʁø, amuʁøz",ua:"(за)кохатися; закоханий",en:"to fall in love; in love",de:"sich verlieben; verliebt"},
{unit:1,theme:"L'amour",fr:"l'être aimé",ipa:"lɛtʁ‿eme",ua:"кохана людина",en:"the loved one",de:"der geliebte Mensch"},
{unit:1,theme:"L'amour",fr:"les histoires de cœur",ipa:"lez‿istwaʁ də kœʁ",ua:"любовні справи",en:"affairs of the heart",de:"die Herzensangelegenheiten"},
{unit:1,theme:"L'amour",fr:"s'amouracher",ipa:"samuʁaʃe",ua:"закохатися, втюритися",en:"to become infatuated",de:"sich vergaffen"},
{unit:1,theme:"L'amour",fr:"(se) séduire",ipa:"sə sedɥiʁ",ua:"зваблювати (одне одного)",en:"to seduce (each other)",de:"(sich) verführen"},
{unit:1,theme:"L'amour",fr:"trouver l'amour",ipa:"tʁuve lamuʁ",ua:"знайти кохання",en:"to find love",de:"die Liebe finden"},
{unit:1,theme:"Les relations humaines",fr:"attachant(e)",ipa:"ataʃɑ̃, ataʃɑ̃t",ua:"привабливий, симпатичний",en:"endearing",de:"liebenswert"},
{unit:1,theme:"Les relations humaines",fr:"débattre",ipa:"debatʁ",ua:"дискутувати, обговорювати",en:"to debate",de:"debattieren"},
{unit:1,theme:"Les relations humaines",fr:"l'échec (m.)",ipa:"leʃɛk",ua:"невдача, провал",en:"failure",de:"der Misserfolg"},
{unit:1,theme:"Les relations humaines",fr:"jaloux, jalouse",ipa:"ʒalu, ʒaluz",ua:"ревнивий; заздрісний",en:"jealous",de:"eifersüchtig"},
{unit:1,theme:"Les relations humaines",fr:"juger",ipa:"ʒyʒe",ua:"судити, оцінювати",en:"to judge",de:"urteilen"},
{unit:1,theme:"Les relations humaines",fr:"la passion",ipa:"la pasjɔ̃",ua:"пристрасть",en:"passion",de:"die Leidenschaft"},
{unit:1,theme:"Les relations humaines",fr:"ravi(e)",ipa:"ʁavi",ua:"у захваті, дуже радий",en:"delighted",de:"hocherfreut"},
{unit:1,theme:"Les relations humaines",fr:"remonter le moral",ipa:"ʁəmɔ̃te lə mɔʁal",ua:"підбадьорити, підняти настрій",en:"to cheer up",de:"aufmuntern"},
{unit:1,theme:"Les relations humaines",fr:"se remettre",ipa:"sə ʁəmɛtʁ",ua:"оговтатися, відновитися",en:"to recover",de:"sich erholen"},
{unit:1,theme:"Les relations humaines",fr:"(se) trahir",ipa:"sə tʁaiʁ",ua:"зраджувати (одне одного)",en:"to betray (each other)",de:"(sich) verraten"},
{unit:1,theme:"Les relations humaines",fr:"voyeur, voyeuse",ipa:"vwajœʁ, vwajøz",ua:"вуайєрист, спостерігач за чужим життям",en:"voyeur",de:"der Voyeur, die Voyeurin"},
{unit:1,theme:"Les personnes",fr:"l'ami(e)",ipa:"lami",ua:"друг, подруга",en:"friend",de:"der Freund, die Freundin"},
{unit:1,theme:"Les personnes",fr:"la bande de potes",ipa:"la bɑ̃d də pɔt",ua:"компанія друзів",en:"group of mates",de:"die Clique"},
{unit:1,theme:"Les personnes",fr:"le compagnon, la compagne",ipa:"lə kɔ̃paɲɔ̃, la kɔ̃paɲ",ua:"супутник життя, партнер(ка)",en:"partner, companion",de:"der Lebensgefährte, die Lebensgefährtin"},
{unit:1,theme:"Les personnes",fr:"l'entourage (m.)",ipa:"lɑ̃tuʁaʒ",ua:"оточення, близькі",en:"circle, those around one",de:"das Umfeld"},
{unit:1,theme:"Les personnes",fr:"le/la meilleur(e) ami(e)",ipa:"lə la mɛjœʁ ami",ua:"найкращий друг / подруга",en:"best friend",de:"der/die beste Freund(in)"},
{unit:1,theme:"Les personnes",fr:"le/la pote",ipa:"lə la pɔt",ua:"приятель, друзяка",en:"mate, buddy",de:"der Kumpel"},
{unit:1,theme:"Les personnes",fr:"le/la proche",ipa:"lə la pʁɔʃ",ua:"близька людина",en:"close one, relative",de:"der/die Nahestehende"},
{unit:1,theme:"Les sentiments",fr:"amical(e)",ipa:"amikal",ua:"дружній",en:"friendly",de:"freundschaftlich"},
{unit:1,theme:"Les sentiments",fr:"l'attraction pour quelqu'un",ipa:"latʁaksjɔ̃",ua:"потяг до когось",en:"attraction to someone",de:"die Anziehung zu jemandem"},
{unit:1,theme:"Les sentiments",fr:"le chagrin",ipa:"lə ʃaɡʁɛ̃",ua:"горе, смуток",en:"sorrow, grief",de:"der Kummer"},
{unit:1,theme:"Les sentiments",fr:"l'espoir (m.)",ipa:"lɛspwaʁ",ua:"надія",en:"hope",de:"die Hoffnung"},
{unit:1,theme:"Les sentiments",fr:"être intégré(e) (dans un groupe)",ipa:"ɛtʁ‿ɛ̃teɡʁe",ua:"бути прийнятим (у групу)",en:"to be integrated (into a group)",de:"(in eine Gruppe) integriert sein"},
{unit:1,theme:"Les sentiments",fr:"être isolé(e)",ipa:"ɛtʁ‿izɔle",ua:"бути ізольованим, самотнім",en:"to be isolated",de:"isoliert sein"},
{unit:1,theme:"Les sentiments",fr:"être mis(e) de côté",ipa:"ɛtʁ mi də kote",ua:"бути відстороненим, відкинутим",en:"to be left out",de:"ausgegrenzt werden"},
{unit:1,theme:"Les sentiments",fr:"être moqué(e)",ipa:"ɛtʁ mɔke",ua:"бути висміяним",en:"to be mocked",de:"verspottet werden"},
{unit:1,theme:"Les sentiments",fr:"l'isolement (m.)",ipa:"lizɔləmɑ̃",ua:"ізоляція, самотність",en:"isolation",de:"die Isolation"},
{unit:1,theme:"Les sentiments",fr:"la joie",ipa:"la ʒwa",ua:"радість",en:"joy",de:"die Freude"},
{unit:1,theme:"Les sentiments",fr:"la peine",ipa:"la pɛn",ua:"смуток, прикрість",en:"sorrow, pain",de:"der Kummer, das Leid"},
{unit:1,theme:"Les sentiments",fr:"se moquer de",ipa:"sə mɔke də",ua:"насміхатися з",en:"to make fun of",de:"sich lustig machen über"},
{unit:1,theme:"Les sentiments",fr:"se sentir seul(e)",ipa:"sə sɑ̃tiʁ sœl",ua:"почуватися самотнім",en:"to feel lonely",de:"sich einsam fühlen"},
{unit:1,theme:"Les sentiments",fr:"le souci",ipa:"lə susi",ua:"турбота, клопіт",en:"worry, concern",de:"die Sorge"},
{unit:1,theme:"Les sentiments",fr:"tendre",ipa:"tɑ̃dʁ",ua:"ніжний",en:"tender, affectionate",de:"zärtlich"},
{unit:1,theme:"Le soutien",fr:"avoir besoin de quelqu'un",ipa:"avwaʁ bəzwɛ̃",ua:"потребувати когось",en:"to need someone",de:"jemanden brauchen"},
{unit:1,theme:"Le soutien",fr:"l'écoute (f.)",ipa:"lekut",ua:"уважність, готовність вислухати",en:"a listening ear",de:"das Zuhören"},
{unit:1,theme:"Le soutien",fr:"l'empathie (f.)",ipa:"lɑ̃pati",ua:"емпатія, співпереживання",en:"empathy",de:"die Empathie"},
{unit:1,theme:"Le soutien",fr:"épauler",ipa:"epole",ua:"підтримувати, допомагати",en:"to support, to back up",de:"unterstützen"},
{unit:1,theme:"Le soutien",fr:"ouvrir ses bras",ipa:"uvʁiʁ se bʁa",ua:"розкрити обійми",en:"to open one's arms",de:"die Arme öffnen"},
{unit:1,theme:"Le soutien",fr:"partager",ipa:"paʁtaʒe",ua:"ділитися",en:"to share",de:"teilen"},
{unit:1,theme:"Le soutien",fr:"réconforter",ipa:"ʁekɔ̃fɔʁte",ua:"втішати, підбадьорювати",en:"to comfort",de:"trösten"},
{unit:1,theme:"Le soutien",fr:"s'occuper de quelqu'un",ipa:"sɔkype",ua:"піклуватися про когось",en:"to take care of someone",de:"sich um jemanden kümmern"},
{unit:1,theme:"Le soutien",fr:"tendre la main",ipa:"tɑ̃dʁ la mɛ̃",ua:"простягнути руку (допомоги)",en:"to lend a hand",de:"die Hand reichen"},
{unit:1,theme:"L'amitié",fr:"briser la glace",ipa:"bʁize la ɡlas",ua:"розтопити лід, зав'язати спілкування",en:"to break the ice",de:"das Eis brechen"},
{unit:1,theme:"L'amitié",fr:"décrocher son téléphone",ipa:"dekʁɔʃe sɔ̃ telefɔn",ua:"зняти слухавку, зателефонувати",en:"to pick up the phone",de:"den Hörer abnehmen"},
{unit:1,theme:"L'amitié",fr:"la différence de caractère",ipa:"la difeʁɑ̃s də kaʁaktɛʁ",ua:"різниця характерів",en:"difference in character",de:"der Charakterunterschied"},
{unit:1,theme:"L'amitié",fr:"l'engagement (m.)",ipa:"lɑ̃ɡaʒmɑ̃",ua:"зобов'язання, відданість",en:"commitment",de:"die Verpflichtung"},
{unit:1,theme:"L'amitié",fr:"être complémentaire",ipa:"ɛtʁ kɔ̃plemɑ̃tɛʁ",ua:"доповнювати одне одного",en:"to be complementary",de:"sich ergänzen"},
{unit:1,theme:"L'amitié",fr:"partager le quotidien",ipa:"paʁtaʒe lə kɔtidjɛ̃",ua:"ділити повсякдення",en:"to share everyday life",de:"den Alltag teilen"},
{unit:1,theme:"L'amitié",fr:"passer du temps ensemble",ipa:"pase dy tɑ̃ ɑ̃sɑ̃bl",ua:"проводити час разом",en:"to spend time together",de:"Zeit zusammen verbringen"},
{unit:1,theme:"L'amitié",fr:"pouffer",ipa:"pufe",ua:"пирхати від сміху",en:"to giggle",de:"kichern"},
{unit:1,theme:"L'amitié",fr:"le rapprochement",ipa:"lə ʁapʁɔʃmɑ̃",ua:"зближення",en:"getting closer, rapprochement",de:"die Annäherung"},
{unit:1,theme:"L'amitié",fr:"rire des mêmes choses",ipa:"ʁiʁ de mɛm ʃoz",ua:"сміятися з одного й того ж",en:"to laugh at the same things",de:"über dasselbe lachen"},
{unit:1,theme:"L'amitié",fr:"se faire des ami(e)s",ipa:"sə fɛʁ dez‿ami",ua:"заводити друзів",en:"to make friends",de:"Freunde finden"},
{unit:1,theme:"L'amitié",fr:"sceller l'amitié",ipa:"sele lamitje",ua:"скріпити дружбу",en:"to seal a friendship",de:"die Freundschaft besiegeln"},
{unit:1,theme:"L'amitié",fr:"la sincérité",ipa:"la sɛ̃seʁite",ua:"щирість",en:"sincerity",de:"die Aufrichtigkeit"},
{unit:1,theme:"L'amitié",fr:"le tabou",ipa:"lə tabu",ua:"табу, заборонена тема",en:"taboo",de:"das Tabu"},

/* — Unité 2 — Vivre ensemble — */
{unit:2,theme:"Les règles de politesse",fr:"appliquer",ipa:"aplike",ua:"застосовувати",en:"to apply",de:"anwenden"},
{unit:2,theme:"Les règles de politesse",fr:"l'autorisation (f.)",ipa:"lotɔʁizasjɔ̃",ua:"дозвіл",en:"permission",de:"die Erlaubnis"},
{unit:2,theme:"Les règles de politesse",fr:"avertir d'un retard",ipa:"avɛʁtiʁ dœ̃ ʁətaʁ",ua:"попередити про запізнення",en:"to give notice of a delay",de:"über eine Verspätung informieren"},
{unit:2,theme:"Les règles de politesse",fr:"les bonnes manières (f.)",ipa:"le bɔn manjɛʁ",ua:"гарні манери",en:"good manners",de:"die guten Manieren"},
{unit:2,theme:"Les règles de politesse",fr:"la familiarité",ipa:"la familjaʁite",ua:"фамільярність",en:"familiarity",de:"die Vertraulichkeit"},
{unit:2,theme:"Les règles de politesse",fr:"gentiment",ipa:"ʒɑ̃timɑ̃",ua:"люб'язно",en:"kindly",de:"freundlich"},
{unit:2,theme:"Les règles de politesse",fr:"la marque de respect",ipa:"la maʁk də ʁɛspɛ",ua:"вияв поваги",en:"a mark of respect",de:"das Zeichen des Respekts"},
{unit:2,theme:"Les règles de politesse",fr:"poli(e)",ipa:"pɔli",ua:"ввічливий",en:"polite",de:"höflich"},
{unit:2,theme:"Les règles de politesse",fr:"la règle de conduite",ipa:"la ʁɛɡl də kɔ̃dɥit",ua:"правило поведінки",en:"a rule of conduct",de:"die Verhaltensregel"},
{unit:2,theme:"Les règles de politesse",fr:"le savoir-vivre",ipa:"lə savwaʁ vivʁ",ua:"уміння поводитися, етикет",en:"good manners, savoir-vivre",de:"die gute Lebensart"},
{unit:2,theme:"Civilités et incivilités",fr:"bafouer",ipa:"bafwe",ua:"зневажати, нехтувати",en:"to flout",de:"missachten"},
{unit:2,theme:"Civilités et incivilités",fr:"respecter",ipa:"ʁɛspɛkte",ua:"поважати",en:"to respect",de:"respektieren"},
{unit:2,theme:"Civilités et incivilités",fr:"céder sa place",ipa:"sede sa plas",ua:"поступитися місцем",en:"to give up one's seat",de:"den Platz freimachen"},
{unit:2,theme:"Civilités et incivilités",fr:"refuser de donner sa place",ipa:"ʁəfyze",ua:"відмовитися поступитися місцем",en:"to refuse to give up one's seat",de:"sich weigern, den Platz freizumachen"},
{unit:2,theme:"Civilités et incivilités",fr:"jeter (des déchets) sur la place publique",ipa:"ʒəte de deʃɛ",ua:"кидати (сміття) в громадському місці",en:"to throw (litter) in a public place",de:"(Abfall) auf öffentlichem Platz wegwerfen"},
{unit:2,theme:"Civilités et incivilités",fr:"se montrer indifférent(e)",ipa:"sə mɔ̃tʁe ɛ̃difeʁɑ̃",ua:"виявляти байдужість",en:"to be indifferent",de:"sich gleichgültig zeigen"},
{unit:2,theme:"L'interaction",fr:"diverger",ipa:"divɛʁʒe",ua:"розходитися (у думках)",en:"to diverge",de:"auseinandergehen"},
{unit:2,theme:"L'interaction",fr:"l'interlocuteur, l'interlocutrice",ipa:"lɛ̃tɛʁlɔkytœʁ",ua:"співрозмовник, співрозмовниця",en:"the interlocutor",de:"der Gesprächspartner, die Gesprächspartnerin"},
{unit:2,theme:"L'interaction",fr:"lancer une conversation",ipa:"lɑ̃se yn kɔ̃vɛʁsasjɔ̃",ua:"розпочати розмову",en:"to start a conversation",de:"ein Gespräch beginnen"},
{unit:2,theme:"L'interaction",fr:"rentrer/entrer en interaction",ipa:"ʁɑ̃tʁe ɑ̃n‿ɛ̃teʁaksjɔ̃",ua:"вступати у взаємодію",en:"to enter into interaction",de:"in Interaktion treten"},
{unit:2,theme:"L'interaction",fr:"répondre",ipa:"ʁepɔ̃dʁ",ua:"відповідати",en:"to answer",de:"antworten"},
{unit:2,theme:"L'interaction",fr:"se dire des choses",ipa:"sə diʁ de ʃoz",ua:"говорити одне одному щось",en:"to say things to each other",de:"sich Dinge sagen"},
{unit:2,theme:"La conscience citoyenne",fr:"l'acte (m.)",ipa:"lakt",ua:"вчинок, дія",en:"the act",de:"die Handlung"},
{unit:2,theme:"La conscience citoyenne",fr:"comprendre dès le plus jeune âge",ipa:"kɔ̃pʁɑ̃dʁ",ua:"розуміти змалку",en:"to understand from a young age",de:"von klein auf verstehen"},
{unit:2,theme:"La conscience citoyenne",fr:"construire",ipa:"kɔ̃stʁɥiʁ",ua:"будувати, формувати",en:"to build",de:"aufbauen"},
{unit:2,theme:"La conscience citoyenne",fr:"éduquer",ipa:"edyke",ua:"виховувати",en:"to educate",de:"erziehen"},
{unit:2,theme:"La conscience citoyenne",fr:"enseigner",ipa:"ɑ̃seɲe",ua:"навчати, викладати",en:"to teach",de:"unterrichten"},
{unit:2,theme:"La conscience citoyenne",fr:"faire partie de",ipa:"fɛʁ paʁti də",ua:"бути частиною",en:"to be part of",de:"Teil sein von"},
{unit:2,theme:"La conscience citoyenne",fr:"sensibiliser",ipa:"sɑ̃sibilize",ua:"підвищувати обізнаність",en:"to raise awareness",de:"sensibilisieren"},
{unit:2,theme:"La conscience citoyenne",fr:"la valeur",ipa:"la valœʁ",ua:"цінність",en:"the value",de:"der Wert"},
{unit:2,theme:"Le vivant et la nature",fr:"l'ADN (m.)",ipa:"ladeɛn",ua:"ДНК",en:"DNA",de:"die DNA"},
{unit:2,theme:"Le vivant et la nature",fr:"la biologie",ipa:"la bjɔlɔʒi",ua:"біологія",en:"biology",de:"die Biologie"},
{unit:2,theme:"Le vivant et la nature",fr:"détruire",ipa:"detʁɥiʁ",ua:"руйнувати, знищувати",en:"to destroy",de:"zerstören"},
{unit:2,theme:"Le vivant et la nature",fr:"l'écologie (f.)",ipa:"lekɔlɔʒi",ua:"екологія",en:"ecology",de:"die Ökologie"},
{unit:2,theme:"Le vivant et la nature",fr:"l'écosystème (m.)",ipa:"lekosistɛm",ua:"екосистема",en:"ecosystem",de:"das Ökosystem"},
{unit:2,theme:"Le vivant et la nature",fr:"l'environnement (m.)",ipa:"lɑ̃viʁɔnmɑ̃",ua:"довкілля",en:"the environment",de:"die Umwelt"},
{unit:2,theme:"Le vivant et la nature",fr:"l'espace naturel (m.)",ipa:"lɛspas natyʁɛl",ua:"природний простір",en:"natural space",de:"der Naturraum"},
{unit:2,theme:"Le vivant et la nature",fr:"explorer",ipa:"ɛksplɔʁe",ua:"досліджувати",en:"to explore",de:"erkunden"},
{unit:2,theme:"Le vivant et la nature",fr:"les fossiles (m.)",ipa:"le fɔsil",ua:"скам'янілості",en:"fossils",de:"die Fossilien"},
{unit:2,theme:"Le vivant et la nature",fr:"la géographie",ipa:"la ʒeɔɡʁafi",ua:"географія",en:"geography",de:"die Geografie"},
{unit:2,theme:"Le vivant et la nature",fr:"le monde animal",ipa:"lə mɔ̃d animal",ua:"тваринний світ",en:"the animal kingdom",de:"die Tierwelt"},
{unit:2,theme:"Le vivant et la nature",fr:"l'observation (f.)",ipa:"lɔpsɛʁvasjɔ̃",ua:"спостереження",en:"observation",de:"die Beobachtung"},
{unit:2,theme:"Le vivant et la nature",fr:"les plantes (f.)",ipa:"le plɑ̃t",ua:"рослини",en:"plants",de:"die Pflanzen"},
{unit:2,theme:"Le vivant et la nature",fr:"protéger",ipa:"pʁɔteʒe",ua:"захищати",en:"to protect",de:"schützen"},
{unit:2,theme:"Le vivant et la nature",fr:"les sciences de la vie (f.)",ipa:"le sjɑ̃s də la vi",ua:"науки про життя",en:"life sciences",de:"die Lebenswissenschaften"},
{unit:2,theme:"Le lien social",fr:"bavarder",ipa:"bavaʁde",ua:"балакати, базікати",en:"to chat",de:"plaudern"},
{unit:2,theme:"Le lien social",fr:"blablater",ipa:"blablate",ua:"теревенити",en:"to chatter, to blabber",de:"quasseln"},
{unit:2,theme:"Le lien social",fr:"chaleureux, chaleureuse",ipa:"ʃalœʁø, ʃalœʁøz",ua:"привітний, сердечний",en:"warm, friendly",de:"herzlich"},
{unit:2,theme:"Le lien social",fr:"convivial(e)",ipa:"kɔ̃vivjal",ua:"привітний, дружній",en:"convivial, friendly",de:"gesellig"},
{unit:2,theme:"Le lien social",fr:"(re)créer du lien",ipa:"ʁəkʁee dy ljɛ̃",ua:"(від)новлювати зв'язок",en:"to (re)build connection",de:"(wieder) Verbindung schaffen"},
{unit:2,theme:"Le lien social",fr:"déshumanisé(e)",ipa:"dezymanize",ua:"знелюднений",en:"dehumanized",de:"entmenschlicht"},
{unit:2,theme:"Le lien social",fr:"échanger des nouvelles",ipa:"eʃɑ̃ʒe de nuvɛl",ua:"обмінюватися новинами",en:"to exchange news",de:"Neuigkeiten austauschen"},
{unit:2,theme:"Le lien social",fr:"faire connaissance",ipa:"fɛʁ kɔnɛsɑ̃s",ua:"знайомитися",en:"to get acquainted",de:"sich kennenlernen"},
{unit:2,theme:"Le lien social",fr:"mettre en relation",ipa:"mɛtʁ ɑ̃ ʁəlasjɔ̃",ua:"налагоджувати зв'язок, зводити",en:"to put in contact",de:"in Verbindung bringen"},
{unit:2,theme:"Le lien social",fr:"papoter",ipa:"papɔte",ua:"теревенити, базікати",en:"to chat, to natter",de:"schwatzen"},
{unit:2,theme:"Le lien social",fr:"se retrouver",ipa:"sə ʁətʁuve",ua:"зустрічатися",en:"to meet up",de:"sich treffen"},
{unit:2,theme:"Le lien social",fr:"sympathiser",ipa:"sɛ̃patize",ua:"заприятелювати",en:"to hit it off",de:"sich anfreunden"},
{unit:2,theme:"L'entraide",fr:"l'aidant, l'aidante",ipa:"lɛdɑ̃, lɛdɑ̃t",ua:"той, хто допомагає, опікун",en:"caregiver, helper",de:"der/die Helfende"},
{unit:2,theme:"L'entraide",fr:"aider",ipa:"ede",ua:"допомагати",en:"to help",de:"helfen"},
{unit:2,theme:"L'entraide",fr:"avoir du temps à donner",ipa:"avwaʁ dy tɑ̃ a dɔne",ua:"мати час, щоб приділити",en:"to have time to give",de:"Zeit zu geben haben"},
{unit:2,theme:"L'entraide",fr:"faire quelque chose pour quelqu'un",ipa:"fɛʁ kɛlkə ʃoz",ua:"робити щось для когось",en:"to do something for someone",de:"etwas für jemanden tun"},
{unit:2,theme:"L'entraide",fr:"prendre soin",ipa:"pʁɑ̃dʁ swɛ̃",ua:"піклуватися",en:"to take care",de:"sich kümmern"},
{unit:2,theme:"L'entraide",fr:"répondre à un besoin",ipa:"ʁepɔ̃dʁ a œ̃ bəzwɛ̃",ua:"задовольняти потребу",en:"to meet a need",de:"einem Bedürfnis entsprechen"},
{unit:2,theme:"L'entraide",fr:"répondre présent(e)",ipa:"ʁepɔ̃dʁ pʁezɑ̃",ua:"відгукнутися, бути готовим допомогти",en:"to be there when needed",de:"zur Stelle sein"},
{unit:2,theme:"L'entraide",fr:"soulager",ipa:"sulaʒe",ua:"полегшувати, давати полегшення",en:"to relieve",de:"entlasten"},
{unit:2,theme:"L'entraide",fr:"le/la volontaire",ipa:"lə la vɔlɔ̃tɛʁ",ua:"волонтер, доброволець",en:"the volunteer",de:"der/die Freiwillige"},
{unit:2,theme:"L'entraide",fr:"le volontariat",ipa:"lə vɔlɔ̃taʁja",ua:"волонтерство",en:"volunteering",de:"das Ehrenamt"},
{unit:2,theme:"L'engagement",fr:"le déclic",ipa:"lə deklik",ua:"осяяння, переломний момент",en:"the trigger, the click",de:"der Auslöser"},
{unit:2,theme:"L'engagement",fr:"dédié(e) (à)",ipa:"dedje",ua:"присвячений (чомусь)",en:"dedicated (to)",de:"gewidmet"},
{unit:2,theme:"L'engagement",fr:"le féminisme",ipa:"lə feminism",ua:"фемінізм",en:"feminism",de:"der Feminismus"},
{unit:2,theme:"L'engagement",fr:"féministe",ipa:"feminist",ua:"феміністичний, феміністка",en:"feminist",de:"feministisch"},
{unit:2,theme:"L'engagement",fr:"l'inspiration (f.)",ipa:"lɛ̃spiʁasjɔ̃",ua:"натхнення",en:"inspiration",de:"die Inspiration"},
{unit:2,theme:"L'engagement",fr:"lutter (pour/contre)",ipa:"lyte",ua:"боротися (за/проти)",en:"to fight (for/against)",de:"kämpfen (für/gegen)"},
{unit:2,theme:"L'engagement",fr:"(re)mettre du sens",ipa:"ʁəmɛtʁ dy sɑ̃s",ua:"повертати сенс",en:"to bring back meaning",de:"(wieder) Sinn geben"},
{unit:2,theme:"L'engagement",fr:"la mise en action",ipa:"la miz ɑ̃n‿aksjɔ̃",ua:"перехід до дії",en:"putting into action",de:"die Umsetzung in die Tat"},
{unit:2,theme:"L'engagement",fr:"la réflexion",ipa:"la ʁeflɛksjɔ̃",ua:"роздуми, обмірковування",en:"reflection",de:"die Überlegung"},

/* — Unité 3 — Cultiver son esprit — */
{unit:3,theme:"Le spectacle",fr:"les applaudissements (m.)",ipa:"lez‿aplodismɑ̃",ua:"оплески",en:"applause",de:"der Applaus"},
{unit:3,theme:"Le spectacle",fr:"la compagnie",ipa:"la kɔ̃paɲi",ua:"трупа, компанія",en:"company (troupe)",de:"die Kompanie"},
{unit:3,theme:"Le spectacle",fr:"les coulisses (f.)",ipa:"le kulis",ua:"лаштунки",en:"the wings (backstage)",de:"die Kulissen"},
{unit:3,theme:"Le spectacle",fr:"l'éclairage (m.)",ipa:"leklɛʁaʒ",ua:"освітлення",en:"lighting",de:"die Beleuchtung"},
{unit:3,theme:"Le spectacle",fr:"la mise en scène",ipa:"la miz‿ɑ̃ sɛn",ua:"постановка, режисура",en:"staging, direction",de:"die Inszenierung"},
{unit:3,theme:"Le spectacle",fr:"le premier/dernier rang",ipa:"lə pʁəmje/dɛʁnje ʁɑ̃",ua:"перший/останній ряд",en:"the front/back row",de:"die erste/letzte Reihe"},
{unit:3,theme:"Le spectacle",fr:"le public",ipa:"lə pyblik",ua:"публіка",en:"the audience",de:"das Publikum"},
{unit:3,theme:"Le spectacle",fr:"la scène",ipa:"la sɛn",ua:"сцена",en:"the stage",de:"die Bühne"},
{unit:3,theme:"Le spectacle",fr:"les sifflets (m.)",ipa:"le siflɛ",ua:"свист (несхвалення)",en:"whistles, booing",de:"die Pfiffe"},
{unit:3,theme:"Le spectacle",fr:"la troupe",ipa:"la tʁup",ua:"трупа",en:"troupe",de:"die Truppe"},
{unit:3,theme:"Le cirque",fr:"l'acrobate (m.)",ipa:"lakʁɔbat",ua:"акробат",en:"acrobat",de:"der Akrobat"},
{unit:3,theme:"Le cirque",fr:"le chapiteau",ipa:"lə ʃapito",ua:"циркове шатро",en:"big top, circus tent",de:"das Zirkuszelt"},
{unit:3,theme:"Le cirque",fr:"le clown",ipa:"lə klun",ua:"клоун",en:"clown",de:"der Clown"},
{unit:3,theme:"Le cirque",fr:"le jongleur, la jongleuse",ipa:"lə ʒɔ̃ɡlœʁ, la ʒɔ̃ɡløz",ua:"жонглер",en:"juggler",de:"der Jongleur, die Jongleurin"},
{unit:3,theme:"Le cirque",fr:"le numéro",ipa:"lə nymeʁo",ua:"номер (виступ)",en:"act, number",de:"die Nummer"},
{unit:3,theme:"Les styles musicaux",fr:"le freestyle",ipa:"lə fʁistajl",ua:"фристайл",en:"freestyle",de:"der Freestyle"},
{unit:3,theme:"Les styles musicaux",fr:"le jazz",ipa:"lə dʒaz",ua:"джаз",en:"jazz",de:"der Jazz"},
{unit:3,theme:"Les styles musicaux",fr:"la musique classique",ipa:"la myzik klasik",ua:"класична музика",en:"classical music",de:"die klassische Musik"},
{unit:3,theme:"Les styles musicaux",fr:"la musique électronique",ipa:"la myzik elɛktʁɔnik",ua:"електронна музика",en:"electronic music",de:"die elektronische Musik"},
{unit:3,theme:"Les styles musicaux",fr:"la pop musique",ipa:"la pɔp myzik",ua:"поп-музика",en:"pop music",de:"die Popmusik"},
{unit:3,theme:"Les styles musicaux",fr:"le rap",ipa:"lə ʁap",ua:"реп",en:"rap",de:"der Rap"},
{unit:3,theme:"Les styles musicaux",fr:"le rock",ipa:"lə ʁɔk",ua:"рок",en:"rock",de:"der Rock"},
{unit:3,theme:"Les styles musicaux",fr:"la variété",ipa:"la vaʁjete",ua:"естрадна музика",en:"popular/variety music",de:"die Schlagermusik"},
{unit:3,theme:"La chanson",fr:"l'album (m.)",ipa:"lalbɔm",ua:"альбом",en:"album",de:"das Album"},
{unit:3,theme:"La chanson",fr:"le compositeur, la compositrice",ipa:"lə kɔ̃pozitœʁ",ua:"композитор",en:"composer",de:"der Komponist, die Komponistin"},
{unit:3,theme:"La chanson",fr:"le disque d'or",ipa:"lə disk dɔʁ",ua:"золотий диск",en:"gold record",de:"die goldene Schallplatte"},
{unit:3,theme:"La chanson",fr:"le duo",ipa:"lə dɥo",ua:"дует",en:"duo",de:"das Duo"},
{unit:3,theme:"La chanson",fr:"le groupe",ipa:"lə ɡʁup",ua:"гурт",en:"band, group",de:"die Gruppe"},
{unit:3,theme:"La chanson",fr:"la mélodie",ipa:"la melɔdi",ua:"мелодія",en:"melody",de:"die Melodie"},
{unit:3,theme:"La chanson",fr:"le rythme",ipa:"lə ʁitm",ua:"ритм",en:"rhythm",de:"der Rhythmus"},
{unit:3,theme:"La chanson",fr:"le single",ipa:"lə siŋɡœl",ua:"сингл",en:"single",de:"die Single"},
{unit:3,theme:"La chanson",fr:"le texte, les paroles (f.)",ipa:"lə tɛkst, le paʁɔl",ua:"текст, слова пісні",en:"lyrics",de:"der Text, die Liedtexte"},
{unit:3,theme:"La chanson",fr:"le tube",ipa:"lə tyb",ua:"хіт",en:"hit (song)",de:"der Hit"},
{unit:3,theme:"Le film",fr:"l'acteur, l'actrice",ipa:"laktœʁ, laktʁis",ua:"актор, акторка",en:"actor, actress",de:"der Schauspieler, die Schauspielerin"},
{unit:3,theme:"Le film",fr:"la bande-annonce",ipa:"la bɑ̃d‿anɔ̃s",ua:"трейлер",en:"trailer",de:"der Trailer"},
{unit:3,theme:"Le film",fr:"la caméra",ipa:"la kameʁa",ua:"камера",en:"camera",de:"die Kamera"},
{unit:3,theme:"Le film",fr:"le casting",ipa:"lə kastiŋ",ua:"акторський склад, кастинг",en:"cast, casting",de:"das Casting"},
{unit:3,theme:"Le film",fr:"le grand écran",ipa:"lə ɡʁɑ̃t‿ekʁɑ̃",ua:"великий екран",en:"the big screen",de:"die große Leinwand"},
{unit:3,theme:"Le film",fr:"l'image (f.)",ipa:"limaʒ",ua:"зображення, кадр",en:"image, picture",de:"das Bild"},
{unit:3,theme:"Le film",fr:"monter",ipa:"mɔ̃te",ua:"монтувати",en:"to edit (a film)",de:"schneiden, montieren"},
{unit:3,theme:"Le film",fr:"le réalisateur, la réalisatrice",ipa:"lə ʁealizatœʁ",ua:"режисер",en:"director",de:"der Regisseur, die Regisseurin"},
{unit:3,theme:"Le film",fr:"le rôle principal",ipa:"lə ʁol pʁɛ̃sipal",ua:"головна роль",en:"lead role",de:"die Hauptrolle"},
{unit:3,theme:"Le film",fr:"le second rôle",ipa:"lə səɡɔ̃ ʁol",ua:"другорядна роль",en:"supporting role",de:"die Nebenrolle"},
{unit:3,theme:"Le film",fr:"la sortie",ipa:"la sɔʁti",ua:"вихід, прем'єра",en:"release",de:"der Kinostart"},
{unit:3,theme:"Les types de films",fr:"l'adaptation (f.)",ipa:"ladaptasjɔ̃",ua:"екранізація, адаптація",en:"adaptation",de:"die Verfilmung"},
{unit:3,theme:"Les types de films",fr:"le blockbuster",ipa:"lə blɔkbystœʁ",ua:"блокбастер",en:"blockbuster",de:"der Blockbuster"},
{unit:3,theme:"Les types de films",fr:"le documentaire",ipa:"lə dɔkymɑ̃tɛʁ",ua:"документальний фільм",en:"documentary",de:"der Dokumentarfilm"},
{unit:3,theme:"Les types de films",fr:"la fiction",ipa:"la fiksjɔ̃",ua:"художній фільм",en:"fiction (film)",de:"der Spielfilm"},
{unit:3,theme:"Les types de films",fr:"le film d'auteur",ipa:"lə film dotœʁ",ua:"авторське кіно",en:"art-house film",de:"der Autorenfilm"},
{unit:3,theme:"Les types de films",fr:"le film grand public",ipa:"lə film ɡʁɑ̃ pyblik",ua:"масове кіно",en:"mainstream film",de:"der Mainstream-Film"},
{unit:3,theme:"Les types de films",fr:"le remake",ipa:"lə ʁimɛk",ua:"ремейк",en:"remake",de:"das Remake"},
{unit:3,theme:"Les types de films",fr:"la suite",ipa:"la sɥit",ua:"продовження, сиквел",en:"sequel",de:"die Fortsetzung"},
{unit:3,theme:"Les types de films",fr:"la superproduction",ipa:"la sypɛʁpʁɔdyksjɔ̃",ua:"масштабна постановка",en:"big-budget production",de:"die Großproduktion"},
{unit:3,theme:"Le scénario",fr:"l'épisode (m.)",ipa:"lepizɔd",ua:"епізод, серія",en:"episode",de:"die Episode, die Folge"},
{unit:3,theme:"Le scénario",fr:"le flashback",ipa:"lə flaʃbak",ua:"флешбек",en:"flashback",de:"die Rückblende"},
{unit:3,theme:"Le scénario",fr:"l'histoire (f.)",ipa:"listwaʁ",ua:"історія, сюжет",en:"story",de:"die Geschichte"},
{unit:3,theme:"Le scénario",fr:"le personnage",ipa:"lə pɛʁsɔnaʒ",ua:"персонаж",en:"character",de:"die Figur"},
{unit:3,theme:"Le scénario",fr:"la saga",ipa:"la saɡa",ua:"сага",en:"saga",de:"die Saga"},
{unit:3,theme:"Le scénario",fr:"se dérouler",ipa:"sə deʁule",ua:"відбуватися, розгортатися",en:"to take place, unfold",de:"sich abspielen"},
{unit:3,theme:"Le scénario",fr:"traiter de",ipa:"tʁɛte də",ua:"розповідати про, бути про",en:"to deal with, be about",de:"handeln von"},
{unit:3,theme:"Les distinctions",fr:"le César",ipa:"lə sezaʁ",ua:"премія «Сезар»",en:"the César (French film award)",de:"der César"},
{unit:3,theme:"Les distinctions",fr:"l'hommage (m.)",ipa:"lɔmaʒ",ua:"вшанування",en:"tribute",de:"die Hommage"},
{unit:3,theme:"Les distinctions",fr:"le jury",ipa:"lə ʒyʁi",ua:"журі",en:"jury",de:"die Jury"},
{unit:3,theme:"Les distinctions",fr:"la récompense",ipa:"la ʁekɔ̃pɑ̃s",ua:"нагорода",en:"award, prize",de:"die Auszeichnung"},
{unit:3,theme:"Les distinctions",fr:"la sélection officielle",ipa:"la selɛksjɔ̃ ɔfisjɛl",ua:"офіційна добірка",en:"official selection",de:"die offizielle Auswahl"},
{unit:3,theme:"Le théâtre",fr:"l'auteur, l'autrice",ipa:"lotœʁ, lotʁis",ua:"автор, авторка",en:"author, playwright",de:"der Autor, die Autorin"},
{unit:3,theme:"Le théâtre",fr:"le comédien, la comédienne",ipa:"lə kɔmedjɛ̃",ua:"актор, акторка (театру)",en:"stage actor, actress",de:"der Schauspieler, die Schauspielerin"},
{unit:3,theme:"Le théâtre",fr:"le décor",ipa:"lə dekɔʁ",ua:"декорація",en:"set, scenery",de:"das Bühnenbild"},
{unit:3,theme:"Le théâtre",fr:"la performance",ipa:"la pɛʁfɔʁmɑ̃s",ua:"гра, виступ",en:"performance",de:"die Darbietung"},
{unit:3,theme:"Le théâtre",fr:"la pièce",ipa:"la pjɛs",ua:"п'єса",en:"play",de:"das Theaterstück"},
{unit:3,theme:"Le théâtre",fr:"la représentation",ipa:"la ʁəpʁezɑ̃tasjɔ̃",ua:"вистава",en:"performance, showing",de:"die Aufführung"},
{unit:3,theme:"Le théâtre",fr:"le rideau",ipa:"lə ʁido",ua:"завіса",en:"curtain",de:"der Vorhang"},
{unit:3,theme:"Le théâtre",fr:"le spectateur, la spectatrice",ipa:"lə spɛktatœʁ",ua:"глядач",en:"spectator",de:"der Zuschauer, die Zuschauerin"},
{unit:3,theme:"Le chef-d'œuvre",fr:"étincelant(e)",ipa:"etɛ̃slɑ̃, etɛ̃slɑ̃t",ua:"іскристий, сяючий",en:"sparkling",de:"funkelnd"},
{unit:3,theme:"Le chef-d'œuvre",fr:"étonnant(e)",ipa:"etɔnɑ̃, etɔnɑ̃t",ua:"дивовижний",en:"astonishing",de:"erstaunlich"},
{unit:3,theme:"Le chef-d'œuvre",fr:"fascinant(e)",ipa:"fasinɑ̃, fasinɑ̃t",ua:"захопливий",en:"fascinating",de:"faszinierend"},
{unit:3,theme:"Le chef-d'œuvre",fr:"féérique",ipa:"feeʁik",ua:"казковий",en:"magical, fairy-tale-like",de:"märchenhaft"},
{unit:3,theme:"Le chef-d'œuvre",fr:"lumineux, lumineuse",ipa:"lyminø, lyminøz",ua:"світлий, осяйний",en:"luminous",de:"leuchtend"},
{unit:3,theme:"Le chef-d'œuvre",fr:"ressentir une émotion",ipa:"ʁəsɑ̃tiʁ yn‿emosjɔ̃",ua:"відчувати емоцію",en:"to feel an emotion",de:"eine Emotion empfinden"},
{unit:3,theme:"Le chef-d'œuvre",fr:"saisissant(e)",ipa:"sɛzisɑ̃, sɛzisɑ̃t",ua:"вражаючий",en:"striking",de:"ergreifend"},
{unit:3,theme:"Le chef-d'œuvre",fr:"surprenant(e)",ipa:"syʁpʁənɑ̃, syʁpʁənɑ̃t",ua:"несподіваний",en:"surprising",de:"überraschend"},
{unit:3,theme:"Le chef-d'œuvre",fr:"symboliser",ipa:"sɛ̃bɔlize",ua:"символізувати",en:"to symbolize",de:"symbolisieren"},
);

/* ---------------- EXPRESSIONS / IDIOMS / INTERJECTIONS ---------------- */
EDITO_EXPR.push(
/* U1 */
{unit:1,fr:"Les amis de nos amis sont nos amis.",ua:"Друзі наших друзів — наші друзі.",en:"A friend of a friend is a friend of mine.",de:"Die Freunde unserer Freunde sind unsere Freunde."},
{unit:1,fr:"Tu as vraiment une famille en or !",ua:"У тебе справді золота сім'я!",en:"You really have a wonderful family!",de:"Du hast wirklich eine goldige Familie!"},
{unit:1,fr:"être fleur bleue",ua:"бути сентиментальним романтиком",en:"to be a hopeless romantic",de:"ein Schwärmer sein"},
{unit:1,fr:"briser la glace",ua:"розтопити лід",en:"to break the ice",de:"das Eis brechen"},
{unit:1,fr:"tendre la main à quelqu'un",ua:"простягнути руку допомоги комусь",en:"to lend someone a hand",de:"jemandem die Hand reichen"},
{unit:1,fr:"J'en garde un excellent souvenir !",ua:"У мене про це чудові спогади!",en:"I have wonderful memories of it!",de:"Ich habe eine herrliche Erinnerung daran!"},
{unit:1,fr:"être trois ou rien",ua:"бути втрьох або ніяк",en:"all three or none at all",de:"zu dritt oder gar nicht"},
{unit:1,fr:"offrir son oreille",ua:"вислухати когось, підставити плече",en:"to lend an ear",de:"ein offenes Ohr haben"},
/* U2 — réactions, appréciations, soutien */
{unit:2,fr:"Quel enfer !",ua:"Який жах! Що за кошмар!",en:"What a nightmare!",de:"Was für ein Albtraum!"},
{unit:2,fr:"Cela me pose problème.",ua:"Це створює мені проблему.",en:"That's a problem for me.",de:"Das ist ein Problem für mich."},
{unit:2,fr:"Ça me gêne.",ua:"Це мене бентежить.",en:"That bothers me.",de:"Das stört mich."},
{unit:2,fr:"Évite de faire ça !",ua:"Не роби так!",en:"Avoid doing that!",de:"Lass das lieber sein!"},
{unit:2,fr:"Tu te trompes !",ua:"Ти помиляєшся!",en:"You're wrong!",de:"Du irrst dich!"},
{unit:2,fr:"C'est triste / dommage / décevant.",ua:"Це сумно / прикро / розчаровує.",en:"That's sad / a shame / disappointing.",de:"Das ist traurig / schade / enttäuschend."},
{unit:2,fr:"On n'a plus le temps de se dire bonjour.",ua:"У нас більше немає часу навіть привітатися.",en:"We no longer have time to say hello to each other.",de:"Wir haben keine Zeit mehr, uns Guten Tag zu sagen."},
{unit:2,fr:"Ça ne me plaît pas du tout de devoir attendre.",ua:"Мені зовсім не подобається бути змушеним чекати.",en:"I really don't like having to wait.",de:"Es gefällt mir gar nicht, warten zu müssen."},
{unit:2,fr:"J'en ai assez de devoir me dépêcher en caisse.",ua:"Мені набридло поспішати на касі.",en:"I'm fed up with having to rush at the checkout.",de:"Ich habe es satt, an der Kasse zu hetzen."},
{unit:2,fr:"Je n'en peux plus de croiser des gens pressés.",ua:"Я більше не можу натикатися на людей, які поспішають.",en:"I can't stand running into people in a hurry anymore.",de:"Ich ertrage es nicht mehr, ständig gehetzten Leuten zu begegnen."},
{unit:2,fr:"Ça m'énerve qu'on doive en arriver là.",ua:"Мене дратує, що до цього дійшло.",en:"It annoys me that it has come to this.",de:"Es nervt mich, dass es so weit kommen musste."},
{unit:2,fr:"Le concept fait mouche.",ua:"Концепція влучає в ціль, має успіх.",en:"The concept hits the mark.",de:"Das Konzept trifft ins Schwarze."},
{unit:2,fr:"(C'est une) chouette / superbe initiative !",ua:"(Це) чудова / прекрасна ініціатива!",en:"(What a) great / wonderful initiative!",de:"(Eine) tolle / großartige Initiative!"},
{unit:2,fr:"Ça fait du bien de retrouver du lien social.",ua:"Приємно знову відчути соціальний зв'язок.",en:"It feels good to reconnect socially.",de:"Es tut gut, wieder sozialen Kontakt zu finden."},
{unit:2,fr:"Je suis ravi(e) de venir ici.",ua:"Я в захваті від того, що приходжу сюди.",en:"I'm delighted to come here.",de:"Ich komme mit Freude hierher."},
{unit:2,fr:"Il est nécessaire de prendre du recul.",ua:"Необхідно подивитися збоку, відсторонитися.",en:"It's necessary to step back and gain perspective.",de:"Man muss Abstand nehmen."},
{unit:2,fr:"Dis-moi si je peux faire quelque chose pour toi.",ua:"Скажи, чи можу я щось для тебе зробити.",en:"Let me know if I can do anything for you.",de:"Sag mir, ob ich etwas für dich tun kann."},
{unit:2,fr:"Je peux être là / présent(e) pour toi.",ua:"Я можу бути поруч / підтримати тебе.",en:"I can be there for you.",de:"Ich kann für dich da sein."},
{unit:2,fr:"N'hésite pas si tu as besoin d'aide !",ua:"Не соромся, якщо тобі потрібна допомога!",en:"Don't hesitate if you need help!",de:"Zögere nicht, wenn du Hilfe brauchst!"},
{unit:2,fr:"Je suis un peu dans l'embarras.",ua:"Я трохи в скрутному становищі.",en:"I'm in a bit of a fix.",de:"Ich bin etwas in Verlegenheit."},
{unit:2,fr:"avoir le moral au plus bas",ua:"бути в дуже пригніченому стані",en:"to feel really down",de:"völlig am Boden sein"},
{unit:2,fr:"peser sur le moral",ua:"гнітити, тиснути на настрій",en:"to weigh on one's spirits",de:"aufs Gemüt schlagen"},
{unit:2,fr:"tenir compagnie",ua:"складати компанію",en:"to keep company",de:"Gesellschaft leisten"},
/* U3 */
{unit:3,fr:"en piste",ua:"на арену; до справи!",en:"on with the show; let's go!",de:"Manege frei; auf geht's!"},
{unit:3,fr:"faire rire petits et grands",ua:"смішити дітей і дорослих",en:"to make young and old laugh",de:"Groß und Klein zum Lachen bringen"},
{unit:3,fr:"mener une vie de bohème",ua:"вести богемне життя",en:"to lead a bohemian life",de:"ein Bohème-Leben führen"},
{unit:3,fr:"être au sommet",ua:"бути на вершині",en:"to be at the top",de:"auf dem Gipfel sein"},
{unit:3,fr:"être reconnu(e) pour",ua:"бути визнаним за",en:"to be renowned for",de:"bekannt sein für"},
{unit:3,fr:"être révélé(e) au grand public",ua:"стати відомим широкому загалу",en:"to be discovered by the general public",de:"einem breiten Publikum bekannt werden"},
{unit:3,fr:"être une (super) star",ua:"бути (супер)зіркою",en:"to be a (super)star",de:"ein (Super-)Star sein"},
{unit:3,fr:"rester interdit / muet / pétrifié",ua:"завмерти, оніміти, скам'яніти",en:"to be left speechless / stunned / petrified",de:"sprachlos / stumm / versteinert bleiben"},
{unit:3,fr:"avoir un choc",ua:"бути шокованим",en:"to be shocked",de:"einen Schock bekommen"},
{unit:3,fr:"faire marcher l'imagination",ua:"будити уяву",en:"to spark the imagination",de:"die Fantasie anregen"},
);

/* ---------------- GRAMMAR (by topic, per unit) ---------------- */
EDITO_GRAMMAR.push(
{unit:1,fr:"Le passé composé et l'imparfait",ua:"Passé composé та imparfait",
 note:"Passé composé — завершена, точкова дія; imparfait — опис, звичка, тривалий контекст у минулому.",
 tables:[{head:["Imparfait","Passé composé"],rows:[
   ["опис, фон, обставини","завершена подія"],
   ["звичка, повторювана дія","одноразова дія"],
   ["Il faisait beau…","…quand il est arrivé."],
 ]}],
 notes:["Imparfait: основа nous (présent) + -ais, -ais, -ait, -ions, -iez, -aient.",
        "Passé composé: avoir/être (présent) + participe passé.",
        "Часто разом: imparfait — тло, passé composé — подія на цьому тлі."]},
{unit:1,fr:"Les indicateurs de temps (1)",ua:"Часові показники (1)",
 note:"il y a / dans — момент; pendant / pour / en — тривалість; depuis і ça fait … que — дія, що триває.",
 tables:[{head:["Вираз","Значення","Приклад"],rows:[
   ["il y a","… тому","Il est parti il y a deux ans."],
   ["dans","через …","Je reviens dans une heure."],
   ["depuis","відтоді, протягом","J'habite ici depuis 2020."],
   ["pendant","протягом","J'ai lu pendant une heure."],
   ["ça fait … que","ось уже … як","Ça fait trois ans que j'apprends."],
 ]}],
 notes:["depuis + теперішній час для дії, що триває досі."]},
{unit:1,fr:"Le plus-que-parfait",ua:"Plus-que-parfait",
 note:"Минуле в минулому: дія, що передує іншій минулій дії.",
 tables:[{head:["Особа","parler","partir (être)"],rows:[
   ["je","j'avais parlé","j'étais parti(e)"],
   ["tu","tu avais parlé","tu étais parti(e)"],
   ["il/elle","il avait parlé","il était parti"],
   ["nous","nous avions parlé","nous étions parti(e)s"],
   ["vous","vous aviez parlé","vous étiez parti(e)s"],
   ["ils/elles","ils avaient parlé","ils étaient partis"],
 ]}],
 notes:["Утворення: être / avoir в imparfait + participe passé.",
        "Quand je suis arrivé, il était déjà parti."]},

{unit:2,fr:"L'interrogation",ua:"Питання (питальні речення)",
 note:"Три регістри питань: інтонація, est-ce que, інверсія.",
 tables:[{head:["Регістр","Форма"],rows:[
   ["розмовний","Tu viens ?"],
   ["стандартний","Est-ce que tu viens ?"],
   ["формальний","Viens-tu ?"],
 ]}],
 notes:["Питальні слова: qui, que/quoi, où, quand, comment, pourquoi, combien, quel."]},
{unit:2,fr:"La nécessité et l'obligation",ua:"Необхідність і обов'язок",
 note:"Загальна необхідність — інфінітив; конкретний суб'єкт — субʼюнктив.",
 tables:[{head:["Конструкція","Приклад"],rows:[
   ["il faut + inf.","Il faut respecter les règles."],
   ["il faut que + subj.","Il faut que tu respectes les règles."],
   ["devoir + inf.","Tu dois arriver à l'heure."],
   ["il est nécessaire que + subj.","Il est nécessaire qu'il vienne."],
 ]}],
 notes:["il faut + інфінітив = загальне правило для всіх.",
        "il faut que + субʼюнктив = звернене до конкретної особи."]},
{unit:2,fr:"Le subjonctif présent",ua:"Субʼюнктив теперішнього часу",
 note:"Вживається після виразів необхідності, бажання, почуттів, сумніву.",
 tables:[{head:["Особа","parler","être","avoir"],rows:[
   ["que je","parle","sois","aie"],
   ["que tu","parles","sois","aies"],
   ["qu'il","parle","soit","ait"],
   ["que nous","parlions","soyons","ayons"],
   ["que vous","parliez","soyez","ayez"],
   ["qu'ils","parlent","soient","aient"],
 ]}],
 notes:["Основа: 3-тя особа множини (ils) présent без -ent + -e, -es, -e, -ent.",
        "nous / vous — як в imparfait.",
        "Неправильні: être, avoir, aller, faire, pouvoir, savoir, vouloir."]},
{unit:2,fr:"Exprimer ses sentiments",ua:"Вираження почуттів",
 note:"Та сама особа — de + інфінітив; інша особа — que + субʼюнктив.",
 tables:[{head:["Та сама особа","Інша особа"],rows:[
   ["Je suis content de venir.","Je suis content que tu viennes."],
   ["J'ai peur de partir.","J'ai peur qu'il parte."],
 ]}],
 notes:["être content / triste / ravi / désolé que + subjonctif.",
        "ça m'énerve / ça me plaît que + subjonctif."]},

{unit:3,fr:"Le conditionnel présent",ua:"Умовний спосіб теперішнього часу",
 note:"Прохання, бажання, порада, припущення, гіпотеза.",
 tables:[{head:["Особа","parler","être","avoir"],rows:[
   ["je","parlerais","serais","aurais"],
   ["tu","parlerais","serais","aurais"],
   ["il/elle","parlerait","serait","aurait"],
   ["nous","parlerions","serions","aurions"],
   ["vous","parleriez","seriez","auriez"],
   ["ils/elles","parleraient","seraient","auraient"],
 ]}],
 notes:["Утворення: основа futur simple + закінчення imparfait (-ais, -ais, -ait, -ions, -iez, -aient).",
        "Ввічливість: Je voudrais… Pourriez-vous… ?",
        "Порада: Tu devrais te reposer."]},
{unit:3,fr:"La restriction (ne… que)",ua:"Обмеження (ne… que)",
 note:"ne… que = «тільки, лише»; que ставиться перед обмежуваним елементом.",
 tables:[{head:["Речення","Значення"],rows:[
   ["Je ne bois que de l'eau.","Я п'ю тільки воду."],
   ["Il n'a qu'un ami.","У нього лише один друг."],
   ["= seulement","Je bois seulement de l'eau."],
 ]}],
 notes:["ne… que не є запереченням — це обмеження.",
        "Синонім: seulement."]},
{unit:3,fr:"La cause et la conséquence",ua:"Причина і наслідок",
 note:"Причина пояснює «чому», наслідок — «що з цього виходить».",
 tables:[{head:["Причина","Наслідок"],rows:[
   ["parce que, car","donc, alors"],
   ["comme, puisque","du coup, c'est pourquoi"],
   ["grâce à (+)","si bien que"],
   ["à cause de (–)","tellement … que"],
 ]}],
 notes:["grâce à — позитивна причина; à cause de — негативна.",
        "comme / puisque ставлять причину на початок речення."]},
);

/* ---------------- VERBS (full B1 tenses, trilingual) ---------------- */
/* Curated set spanning Units 1–3 and every conjugation pattern.        */
EDITO_VERBS.push(
// — core auxiliaries & irregulars —
{unit:1,fr:"être",ua:"бути",en:"to be",de:"sein",example:"Je suis ravi de te voir.",
 conj:irrVerb("être",{aux:"avoir",pp:"été",futStem:"ser",
   pres:["je suis","tu es","il est","nous sommes","vous êtes","ils sont"],
   impf:["j'étais","tu étais","il était","nous étions","vous étiez","ils étaient"],
   subj:["que je sois","que tu sois","qu'il soit","que nous soyons","que vous soyez","qu'ils soient"],
   imp:["sois","soyons","soyez"]})},
{unit:1,fr:"avoir",ua:"мати",en:"to have",de:"haben",example:"J'ai besoin de toi.",
 conj:irrVerb("avoir",{aux:"avoir",pp:"eu",futStem:"aur",
   pres:["j'ai","tu as","il a","nous avons","vous avez","ils ont"],
   subj:["que j'aie","que tu aies","qu'il ait","que nous ayons","que vous ayez","qu'ils aient"],
   imp:["aie","ayons","ayez"]})},
{unit:1,fr:"faire",ua:"робити",en:"to do, to make",de:"machen, tun",example:"On a fait connaissance hier.",
 conj:irrVerb("faire",{aux:"avoir",pp:"fait",futStem:"fer",
   pres:["je fais","tu fais","il fait","nous faisons","vous faites","ils font"],
   subj:["que je fasse","que tu fasses","qu'il fasse","que nous fassions","que vous fassiez","qu'ils fassent"],
   imp:["fais","faisons","faites"]})},
{unit:2,fr:"aller",ua:"йти, їхати",en:"to go",de:"gehen",example:"Je vais t'aider.",
 conj:irrVerb("aller",{aux:"être",pp:"allé",futStem:"ir",agree:true,
   pres:["je vais","tu vas","il va","nous allons","vous allez","ils vont"],
   subj:["que j'aille","que tu ailles","qu'il aille","que nous allions","que vous alliez","qu'ils aillent"],
   imp:["va","allons","allez"]})},
{unit:1,fr:"naître",ua:"народжуватися",en:"to be born",de:"geboren werden",example:"Elle est née en 2001.",
 conj:irrVerb("naître",{aux:"être",pp:"né",futStem:"naîtr",agree:true,
   pres:["je nais","tu nais","il naît","nous naissons","vous naissez","ils naissent"]})},
{unit:1,fr:"rire",ua:"сміятися",en:"to laugh",de:"lachen",example:"Nous rions des mêmes choses.",
 conj:irrVerb("rire",{aux:"avoir",pp:"ri",futStem:"rir",
   pres:["je ris","tu ris","il rit","nous rions","vous riez","ils rient"]})},
{unit:1,fr:"prendre",ua:"брати",en:"to take",de:"nehmen",example:"Je prends soin de mes amis.",
 conj:irrVerb("prendre",{aux:"avoir",pp:"pris",futStem:"prendr",
   pres:["je prends","tu prends","il prend","nous prenons","vous prenez","ils prennent"]})},
{unit:2,fr:"comprendre",ua:"розуміти",en:"to understand",de:"verstehen",example:"Les enfants comprennent dès le plus jeune âge.",
 conj:irrVerb("comprendre",{aux:"avoir",pp:"compris",futStem:"comprendr",
   pres:["je comprends","tu comprends","il comprend","nous comprenons","vous comprenez","ils comprennent"]})},
{unit:1,fr:"mettre",ua:"класти, ставити",en:"to put",de:"setzen, stellen, legen",example:"On les met en relation.",
 conj:irrVerb("mettre",{aux:"avoir",pp:"mis",futStem:"mettr",
   pres:["je mets","tu mets","il met","nous mettons","vous mettez","ils mettent"]})},
{unit:2,fr:"construire",ua:"будувати",en:"to build",de:"bauen",example:"Ils construisent un avenir commun.",
 conj:irrVerb("construire",{aux:"avoir",pp:"construit",futStem:"construir",
   pres:["je construis","tu construis","il construit","nous construisons","vous construisez","ils construisent"]})},
{unit:2,fr:"détruire",ua:"руйнувати, знищувати",en:"to destroy",de:"zerstören",example:"La pollution détruit l'écosystème.",
 conj:irrVerb("détruire",{aux:"avoir",pp:"détruit",futStem:"détruir",
   pres:["je détruis","tu détruis","il détruit","nous détruisons","vous détruisez","ils détruisent"]})},
{unit:2,fr:"vivre",ua:"жити",en:"to live",de:"leben",example:"Nous vivons ensemble.",
 conj:irrVerb("vivre",{aux:"avoir",pp:"vécu",futStem:"vivr",
   pres:["je vis","tu vis","il vit","nous vivons","vous vivez","ils vivent"]})},
{unit:1,fr:"connaître",ua:"знати, бути знайомим",en:"to know (be acquainted)",de:"kennen",example:"Je connais bien ce quartier.",
 conj:irrVerb("connaître",{aux:"avoir",pp:"connu",futStem:"connaîtr",
   pres:["je connais","tu connais","il connaît","nous connaissons","vous connaissez","ils connaissent"]})},
{unit:2,fr:"devoir",ua:"бути зобов'язаним, мусити",en:"must, to have to",de:"müssen",example:"Tu dois respecter les règles.",
 conj:irrVerb("devoir",{aux:"avoir",pp:"dû",futStem:"devr",
   pres:["je dois","tu dois","il doit","nous devons","vous devez","ils doivent"],
   subj:["que je doive","que tu doives","qu'il doive","que nous devions","que vous deviez","qu'ils doivent"],
   imp:["—","—","—"]})},
{unit:2,fr:"pouvoir",ua:"могти",en:"can, to be able to",de:"können",example:"Je peux être là pour toi.",
 conj:irrVerb("pouvoir",{aux:"avoir",pp:"pu",futStem:"pourr",
   pres:["je peux","tu peux","il peut","nous pouvons","vous pouvez","ils peuvent"],
   subj:["que je puisse","que tu puisses","qu'il puisse","que nous puissions","que vous puissiez","qu'ils puissent"],
   imp:["—","—","—"]})},
{unit:2,fr:"vouloir",ua:"хотіти",en:"to want",de:"wollen",example:"Je voudrais t'aider.",
 conj:irrVerb("vouloir",{aux:"avoir",pp:"voulu",futStem:"voudr",
   pres:["je veux","tu veux","il veut","nous voulons","vous voulez","ils veulent"],
   subj:["que je veuille","que tu veuilles","qu'il veuille","que nous voulions","que vous vouliez","qu'ils veuillent"],
   imp:["veuille","voulons","veuillez"]})},
// — regular -IR (finir-type) —
{unit:1,fr:"grandir",ua:"рости, дорослішати",en:"to grow up",de:"aufwachsen",example:"Les enfants grandissent vite.",
 conj:irVerb("grandir")},
{unit:1,fr:"trahir",ua:"зраджувати",en:"to betray",de:"verraten",example:"Un ami ne te trahit pas.",
 conj:irVerb("trahir")},
{unit:2,fr:"avertir",ua:"попереджати",en:"to warn, to notify",de:"benachrichtigen",example:"Il faut avertir d'un retard.",
 conj:irVerb("avertir")},
// — regular -RE —
{unit:2,fr:"répondre",ua:"відповідати",en:"to answer",de:"antworten",example:"Elle répond toujours présente.",
 conj:reVerb("répondre")},
// — regular -ER (incl. -ger / -cer / stem-change) —
{unit:2,fr:"aider",ua:"допомагати",en:"to help",de:"helfen",example:"J'aide mes voisins.",
 conj:erVerb("aider")},
{unit:1,fr:"aimer",ua:"любити, кохати",en:"to love, to like",de:"lieben, mögen",example:"J'aime passer du temps avec eux.",
 conj:erVerb("aimer")},
{unit:1,fr:"partager",ua:"ділитися",en:"to share",de:"teilen",example:"Nous partageons de bons moments.",
 conj:erVerb("partager")},
{unit:1,fr:"juger",ua:"судити, оцінювати",en:"to judge",de:"urteilen",example:"Ne juge pas trop vite.",
 conj:erVerb("juger")},
{unit:2,fr:"lancer",ua:"кидати; розпочинати",en:"to throw; to start",de:"werfen; starten",example:"Il lance la conversation.",
 conj:erVerb("lancer")},
{unit:2,fr:"respecter",ua:"поважати",en:"to respect",de:"respektieren",example:"Nous respectons les règles.",
 conj:erVerb("respecter")},
{unit:2,fr:"protéger",ua:"захищати",en:"to protect",de:"schützen",example:"Protégeons la nature.",
 conj:erVerb("protéger",{futStem:"protéger",
   pres:["je protège","tu protèges","il protège","nous protégeons","vous protégez","ils protègent"]})},
{unit:2,fr:"céder",ua:"поступатися",en:"to give up, to yield",de:"nachgeben, überlassen",example:"Il cède sa place aux aînés.",
 conj:erVerb("céder",{futStem:"céder",
   pres:["je cède","tu cèdes","il cède","nous cédons","vous cédez","ils cèdent"]})},
{unit:2,fr:"jeter",ua:"кидати, викидати",en:"to throw (away)",de:"werfen",example:"Ne jette pas de déchets ici.",
 conj:erVerb("jeter",{futStem:"jetter",
   pres:["je jette","tu jettes","il jette","nous jetons","vous jetez","ils jettent"]})},
{unit:3,fr:"monter",ua:"монтувати; підніматися",en:"to edit (film); to go up",de:"schneiden; hinaufgehen",example:"Il monte son premier film.",
 conj:erVerb("monter")},
{unit:3,fr:"symboliser",ua:"символізувати",en:"to symbolize",de:"symbolisieren",example:"Cette scène symbolise l'espoir.",
 conj:erVerb("symboliser")},
);
